In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup pf tea',
    'I am a developer',
    'I am oaky',
    'I have no problem with my life',
    'Evreything is going well'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup pf tea',
 'I am a developer',
 'I am oaky',
 'I have no problem with my life',
 'Evreything is going well']

In [5]:
voc_size=10000

In [6]:
one_hot_rep=[one_hot(words,voc_size)for words in sent]

In [7]:
one_hot_rep

[[2023, 5633, 6121, 2112],
 [2023, 5633, 6121, 4009],
 [2023, 7216, 6395, 7938],
 [1291, 7323, 6226, 3671],
 [1291, 7323, 3183],
 [1291, 5045, 2793, 4152, 3843, 1508, 4412],
 [4985, 5484, 461, 6268]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2023 5633 6121 2112]
 [   0    0    0    0 2023 5633 6121 4009]
 [   0    0    0    0 2023 7216 6395 7938]
 [   0    0    0    0 1291 7323 6226 3671]
 [   0    0    0    0    0 1291 7323 3183]
 [   0 1291 5045 2793 4152 3843 1508 4412]
 [   0    0    0    0 4985 5484  461 6268]]


In [13]:
dim=10

In [16]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 428ms/step


array([[[-0.03484048,  0.02022039, -0.04064518, -0.00567522,
          0.02437428,  0.04951308, -0.00360025, -0.01682439,
          0.03097996, -0.03030583],
        [-0.03484048,  0.02022039, -0.04064518, -0.00567522,
          0.02437428,  0.04951308, -0.00360025, -0.01682439,
          0.03097996, -0.03030583],
        [-0.03484048,  0.02022039, -0.04064518, -0.00567522,
          0.02437428,  0.04951308, -0.00360025, -0.01682439,
          0.03097996, -0.03030583],
        [-0.03484048,  0.02022039, -0.04064518, -0.00567522,
          0.02437428,  0.04951308, -0.00360025, -0.01682439,
          0.03097996, -0.03030583],
        [-0.00103979,  0.0284475 , -0.03434805, -0.04195438,
         -0.01692721,  0.04200764, -0.01679211, -0.04467488,
         -0.03451265,  0.04283651],
        [ 0.01983878,  0.03775283,  0.01963404,  0.00219226,
          0.04047172,  0.04847492,  0.0036888 ,  0.00138934,
         -0.01334065, -0.01566272],
        [ 0.04906887,  0.02973418,  0.02763555, -0.0